create table web_request_logs (
    id integer generated by default as identity,
    data timestamp,
    ip varchar(255),
    request varchar(255),
    status integer,
    user_agent varchar(255),
    primary key (id)
)
